# Generated by Django 5.2.7 on 2025-10-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_phone_no', models.CharField(max_length=15, unique=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=100)),
                ('user_confirm_password', models.CharField(max_length=100)),
                ('user_Aadhar', models.CharField(max_length=12, unique=True)),
                ('user_location', models.CharField(max_length=150)),
            ],
        ),
    ]
